---
output: 
  pdf_document:
    latex_engine: pdflatex
    template: ~/Dropbox/Documents/job_stuff/markdown_cv/rap-latex-cv.tex
geometry: margin=1in

title: "CV"
author: Monica W. Gerber

#jobtitle: "Biostatistician"
#address: "Massachusetts General Hospital · Boston"
fontawesome: yes
email: mwgerber@gmail.com
github: monicagerber
#phone: "+353 1 408 4800"
web: www.monicagerber.com
updated: no

keywords: R Markdown, academic CV, template

fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 11pt
linkcolor: blue
urlcolor: blue
---

# EDUCATION

*Boston University School of Public Health*, M.P.H., Biostatistics & Epidemiology \hfill 2015

*Reed College*, B.A., Anthropology \hfill 2011

# EMPLOYMENT

**Biostatistician**, *Massachusetts General Hospital | Boston, MA* \hfill Jan. 2015--present

* Build statistical models and analyze large datasets from RCTs, longitudinal studies, electronic health records, and surveys to understand the distribution and determinants of health.
* Collaborate with doctors, researchers, and stakeholders to turn research questions into actionable analysis plans.
* Communicate results through data visualizations, writing, data tables, and interactive apps.
* Extract clinical and real world data from EHRs, claims, and other large databases.
* Mentor and support students and fellows in biostatistics and the preparation of manuscripts.


**Graduate Research Assistant**, *BU School of Public Health | Boston, MA* \hfill Jun.--Dec. 2014

* In the department of Community Health Sciences, I analyzed data from the YRBS using mixed models to understand youth substance use.
* Developed an index to measure exposure to state-level substance use policies.

**Spotlight Coordinator**, *BU School of Public Health | Boston, MA* \hfill May--Dec. 2014

* Launched Spotlight on Mental Health, a school-wide initiative to examine issues in mental health from an interdisciplinary public health lens. 
* Led and supported a faculty, student, and staff committee overseeing Spotlight.
* Planned campus events and programs. Managed communications, marketing, and outreach.


**Consultant Resource Development Specialist**, *Health Leads | Boston, MA* \hfill Oct.--Dec. 2013

* Conducted an audit to improve quality of resources in the Salesforce database.
* Developed methods for better data management. 

**AmeriCorps VISTA Member**, *Oregon Campus Compact | Portland, OR* \hfill Apr. 2012--Aug. 2013

* Team Leader for 34 Summer AmeriCorps Members serving in public schools.
* Developed content and built out organizational website.
* Reported and mapped educational outcomes for state using public data and GIS software.
* Managed marketing, communications, fundraising, events, and volunteer outreach.

**Global Envision Intern**, *Mercy Corps | Portland, OR* \hfill Nov. 2011--Apr. 2012

* Wrote articles about globalization and solutions to poverty for Mercy Corps' blog.


# TEACHING

**Graduate Teaching Assistant**, *Boston University School of Public Health* \hfill 2014--2015

* Introduction to Epidemiology (EP713), Fall 2015, Ann Aschengrau
* Introduction to Epidemiology (EP713), Fall 2014, Jacey Greece

# SKILLS

  - Data Science: R, SQL, SAS, Github/Gitlab, markdown
  - Epidemiology: Causal inference, study design, questionnaire design, methods for bias and confounding.
  - Biostatistics: Advanced statistical modeling, missing data methods, model selection, propensity score analysis.
  - Other: Writing and communication to technical and general audiences, mixed methods analysis, ethnographic methods


# PUBLICATIONS

Whooten, R.C., Perkins, M.E., **Gerber, M.W.** and Taveras, E.M., 2018. Effects of Before-School Physical Activity on Obesity Prevention and Wellness. American journal of preventive medicine.

Valentine, S.E., Nobles, C.J., **Gerber, M.W.**, Vaewsorn, A.S., Shtasel, D.L. and Marques, L., 2017. The association of posttraumatic stress disorder and chronic medical conditions by ethnicity. Journal of Latina/o psychology, 5(3), p.227.

Fiechtner, L., Puente, G.C., Sharifi, M., Block, J.P., Price, S., Marshall, R., Blossom, J., **Gerber, M.W.** and Taveras, E.M., 2017. Peer Reviewed: A Community Resource Map to Support Clinical–Community Linkages in a Randomized Controlled Trial of Childhood Obesity, Eastern Massachusetts, 2014–2016. Preventing chronic disease, 14.

Taveras, E.M., Marshall, R., Sharifi, M., Avalon, E., Fiechtner, L., Horan, C., **Gerber, M.W.**, Orav, E.J., Price, S.N., Sequist, T. and Slater, D., 2017. Comparative effectiveness of clinical-community childhood obesity interventions: a randomized clinical trial. JAMA pediatrics, 171(8), pp.e171325-e171325.

Nobles, C.J., Valentine, S.E., **Gerber, M.W.**, Shtasel, D.L. and Marques, L., 2016. Predictors of treatment utilization and unmet treatment need among individuals with posttraumatic stress disorder from a national sample. General hospital psychiatry, 43, pp.38-45.

Nobles, C.J., Valentine, S.E., Borba, C.P., **Gerber, M.W.**, Shtasel, D.L. and Marques, L., 2016. Black-white disparities in the association between posttraumatic stress disorder and chronic illness. Journal of psychosomatic research, 85, pp.19-25.

Nobles, C.J., Thomas, J.J., Valentine, S.E., **Gerber, M.W.**, Vaewsorn, A.S. and Marques, L., 2016. Association of premenstrual syndrome and premenstrual dysphoric disorder with bulimia nervosa and binge‐eating disorder in a nationally representative epidemiological sample. International Journal of Eating Disorders, 49(7), pp.641-650.

LeBlanc, N.J., Dixon, L., Robinaugh, D.J., Valentine, S.E., Bosley, H.G., **Gerber, M.W.** and Marques, L., 2016. PTSD and Romantic Relationship Satisfaction: Cluster‐and Symptom‐Level Analyses. Journal of traumatic stress, 29(3), pp.259-267.

Valentine, S.E., **Gerber, M.W.**, Nobles, C.J., Shtasel, D.L. and Marques, L., 2016. Longitudinal study of mental health and pain-related functioning following a motor vehicle collision. Health psychology, 35(7), p.742.


# PRESENTATIONS

**Gerber, M.W.**, Fiechtner, L., Horan, C., Orav, E.J., Taveras, E.M. Clinical-Community Intervention for Childhood Obesity: Effect Modification by Socio-Demographic Groups. Poster Presentation: Society of Epidemiologic Research Annual Meeting 2017, Seattle, WA.

**Gerber, M.W,**. Ziming X., Naimi T. Marijuana policy environment and youth marijuana use: The influence of state-level decriminalization and medical marijuana laws. Poster Presentation: Research Days 2014, Evans Memorial Department of Medicine, Boston University, Boston, MA.

 
# OTHER EXPERIENCE AND SERVICE

**Meet-up Organizer**, *[Boston R-Ladies](https://rladies.org/)* \hfill Mar. 2018--present

R-ladies is a world-wide organization to promote gender diversity in the R community.

**Science Fair Mentor**, *[MGH Timilty Middle School Partnership](http://www.massgeneral.org/cchi/services/treatmentprograms.aspx?id=1265)* \hfill Oct. 2017--Feb. 2018

**Budget Commitee Member**, *[City of Cambridge Participatory Budegeting](https://pb.cambridgema.gov/)* \hfill 2016 and 2017 cycles

Participatory budgeting is a democratic process through which the community decides how to spend part of the city's budget. I evaluated ideas from community and developed them into projects for the ballot. 

**Volunteer**, *[YWCA of Greater Portland](https://www.ywcapdx.org/)* \hfill Feb. 2012--Jun. 2013

Completed a 30-hour training in domestic violence issues, volunteered at the YWCA's shelter, and supported development projects.  


  
